name = "hatchman"
pages_build_output_dir = "dist"
compatibility_date = "2026-09-21"

[[r2_buckets]]
binding = "MEDIA"
bucket_name = "hatchman-media"
preview_bucket_name = "hatchman-media"

[[env.production.r2_buckets]]
binding = "MEDIA"
bucket_name = "hatchman-media"
